### ISSUE TITLE
Minor issues in desassembling tables

### ISSUE THREAD

**Issue by rgiot** [jeromelesaux/dsk#1]
I have stolen the tables from the disassembling code for my own library: https://github.com/cpcsdk/rust.cpclib

When launching my unit tests, I have discovered some issues (or, least they seem to be issues in view to other ressources on z80):
- Presence of impossible opcodes:
  * ADD IX, HL
  * ADD IY, HL 
- Exchange of opcodes:
 * RET PO and RET PE
 * CALL PO and CALL PE (if I remember well)

I have not finished my implementation; so I may have forgotten some others

**Comment by rgiot** [comment]
I also suspect a line of empty opcodes is missing before `"IN B,(C)", "OUT (C),B", "SBC HL,BC", "LD (nnnn),BC",`
without it, the opcodes are not correct

**Comment by jeromelesaux** [comment]
Thanks for those reports. 
I 'll do some tests on my side. 
I'll check all those issues.

**Comment by jeromelesaux** [comment]
I fixed the exchange of opcodes. 
I continue to look for the missing opcodes.

**Comment by jeromelesaux** [comment]
for the missing line to you remember what is missing ?

**Comment by jeromelesaux** [comment]
if I check some referenced sites like http://z80-heaven.wikidot.com/opcode-reference-chart. 
There is nothing before.

**Comment by jeromelesaux** [comment]
all fixes are committed, you can check them.

**Comment by rgiot** [comment]
Seems good for me. 
I think in commit 12a9dd4d469a860beaf26ae87d08c01635651b96 is not complete and should more look like

	"RET PO", "POP HL", "JP PO,nnnn", "EX (SP),HL", 
	"CALL PO,nnnn", "PUSH HL", "AND nn", "RST 20",
	"RET PE", "JP (HL)", "JP PE,nnnn", "EX DE,HL",
	"CALL PE,nnnn", "", "XOR nn", "RST 28",

Looking at your patches I identify an error in my code; thanks ;)

For the missing line, I do not remember. It was a table that has not 256 elements (but it was maybe a copy/paste error). Go does not signal that ?

**Comment by jeromelesaux** [comment]
fixed in main opcodes table. 
For the missing line, I'm pretty sur there is not missing line, but I may be in error.

**Comment by jeromelesaux** [comment]
is it ok for you ?
May I close this issue  ?

**Comment by rgiot** [comment]
yep; thanks again for your project

**Comment by jeromelesaux** [comment]
thanks to you to spend some time on the source code ^^.
