### ISSUE TITLE
Ergonomie de la ligne de commande

### ISSUE THREAD

**Issue by EdouardBERGE** [jeromelesaux/dsk#2]
quelques remarques pour que le programme soit agréable à utiliser ;)

- si t'as une option qui n'existe pas => affichage des options
- si t'as une erreur sur un paramètre d'option => affichage d'un message spécifique à l'option et uniquement cette option
- si t'as une erreur à l'exécution du programme => ne PAS afficher les options, là le message d'erreur (quand il est là) est noyé au début du programme

**Comment by jeromelesaux** [comment]
je viens d'ajouter un mécanisme qui ajoute un conseil lors d'une erreur trouvée. 
cela devrait faciliter l'usage de l'outil. 
A voir dans la prochaine version 0.11

**Comment by jeromelesaux** [comment]
pris en compte dans la dernière release.
