### ISSUE TITLE
L'ordre des options ne doit pas influencer le comportement du programme

### ISSUE THREAD

**Issue by EdouardBERGE** [jeromelesaux/dsk#3]
Si je mets un -get ficheir suivi d'un -dsk fichierdsk il ne trouve pas la disquette

A minima, si les options doivent être déclarées dans un certain ordre il faut en informer l'utilisateur => sinon, laisser faire la déclaration des options dans n'importe quel ordre

**Comment by jeromelesaux** [comment]
ceci est vrai, il n'y a pas d'ordre des options, il faut juste que j'ajoute une documentation adéquate pour mieux comprendre son usage.

**Comment by jeromelesaux** [comment]
pris en compte dans la dernière release.
