### ISSUE TITLE
Option -get et -put

### ISSUE THREAD

**Issue by EdouardBERGE** [jeromelesaux/dsk#4]
L'option -get ne récupère pas un fichier sur le DSK, il faut lui ajouter une option (-amsdosfile, une autre?)

=> soit changer l'aide de cette option pour préciser qu'elle ne peut pas fonctionner de la sorte
=> soit récupérer le fichier

j'suis chiant hein? :p

**Comment by jeromelesaux** [comment]
Nan pas du tout ^^. Si tu te poses la question d'autres personnes se sont posées cette question. 

-get et -put sont des options d'action qui nécessitent d'être associées avec l'option -amsdosfile pour appliquer les changements.
J'ai ajouté plus d'informations lors des erreurs pour que cela soit plus clair pour les utilisateurs.

**Comment by jeromelesaux** [comment]
pris en compte dans la dernière release.
