### ISSUE TITLE
corruption de fichier

### ISSUE THREAD

**Issue by grim1z** [jeromelesaux/dsk#5]
Quand je fais un put dans un dsk d'un fichier en mode ascii, il est corrompu (des octets &3F apparaissent de temps en temps à la place des bonnes valeurs). Le fichier en question est un fichier de 19ko qui contient des données binaires (pas que des caractères ASCII), c'est peut-être l'origine du problème.

**Comment by jeromelesaux** [comment]
bonjour Grim1z, est il possible de me donner un exemple de fichier qui ne fonctionne pas bien ? je vais regarder de mon côté le souci.

**Comment by grim1z** [comment]
Merci, voilà par exemple un fichier random avant et après un put/get dans un dsk.
(btw, je suis Zik)

[tst_files.zip](https://github.com/jeromelesaux/dsk/files/6335177/tst_files.zip)

**Comment by jeromelesaux** [comment]
je regarde ça maintenant.

**Comment by jeromelesaux** [comment]
le fichier tst1005.tst est le fichier original ?

**Comment by grim1z** [comment]
Pour être plus précis :
- tst1005.tst_orig = fichier de départ
- tst1005.tst = le fichier récupéré après un put/get
- tst1005.tst_expected = ce à quoi je me serais attendu (&1a ajouté à la fin puis padding à une taille multiple de 128 avec une valeur random)

[tst_files2.zip](https://github.com/jeromelesaux/dsk/files/6335211/tst_files2.zip)

**Comment by jeromelesaux** [comment]
je viens de regarder mon code, et effectivement je fais un traitement à savoir si on est en mode ascii tout se qui est supérieur à 136 (valeur maximal d'un caractère affichable) je le remplace. 
Veux tu que j'enlève ce comportement ?

**Comment by grim1z** [comment]
Oui, l'Amsdos ne fait pas ça, tous les codes sont valides.
Et si la taille du fichier n'est pas multiple de 128 octets, un caractère "soft end of file" &1A est ajouté au fichier.

**Comment by jeromelesaux** [comment]
c'est corrigé. voici une version linux pour tester. [](url)
[dsk-0.12-linux-amd64.zip](https://github.com/jeromelesaux/dsk/files/6336057/dsk-0.12-linux-amd64.zip)

**Comment by grim1z** [comment]
Merci, ça semble tout bon :)

Il y a un autre problème sur l'arrondi de la taille au bloc de 128 octet supérieur.
Par exemple avec ce fichier de test. Il devrait passer de 18511 à 18560, mais il augmente à 19456 (à priori l'arrondi se fait à 1024 près au lieu de 128).
[tst_files3.zip](https://github.com/jeromelesaux/dsk/files/6336246/tst_files3.zip)

**Comment by jeromelesaux** [comment]
je regarde merci pour les infos.

**Comment by jeromelesaux** [comment]
je viens d'ajouter une correction. Veux tu attendre la release ou je te fournir une version ici pour tester ?

**Comment by grim1z** [comment]
Je peux attendre la release, merci.

**Comment by jeromelesaux** [comment]
ok je la fournis ce soir ^^
